spring.application.name=sigha
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Fuerza el search_path de cada conexión al esquema del programa + core
spring.datasource.hikari.connection-init-sql=SET search_path TO "${DEFAULT_SCHEMA_SISTEMAS}", core
spring.jpa.properties.hibernate.default_schema=${DEFAULT_SCHEMA_SISTEMAS}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.secret.key=${APP_SECRET_KEY}

# Zona horaria para serializaci�n JSON
spring.jackson.time-zone=America/Bogota

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
email.fake.destination=${EMAIL_FAKE_DESTINATION}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

sigha.url.access=${SIGHA_URL_ACCESS}

